In [1]:
from uk.ac.ebi.vfb.neo4j.KB_tools import KB_pattern_writer
import pandas as pd
from ontobio import OntologyFactory
import re
import yaml

#local_test = KB_pattern_writer('http://localhost:7474', 'neo4j', 'neo4j')
#kb = KB_pattern_writer('http://kb.virtualflybrain.org', 'neo4j', 'neo4j')
kbw = KB_pattern_writer('http://kbw.virtualflybrain.org:7474', 'neo4j', 'baNi8HaC')

OF = OntologyFactory()
fbbt = OF.create("/repos/drosophila-anatomy-developmental-ontology/fbbt/releases/fbbt.json")
mapping_table = pd.read_csv("./IndexKey_neuropils_only.tsv", sep='\t')

#template_yaml = yaml.load(yf.read())
#mapping_table.set_index("Index", inplace=True)

mapping_table
# print(template_yaml)
#c = ['label', 'synonyms', 'Index', 'centre','anatomical_type'] 

#[fbbt.label(re.sub('_', ':', x)) for x in mapping_table['Class_ID']]

,Index,Ind_ID,Class_ID,Name,Abbreviation,Note,Centre,Colour
0,1,VFB_00050002,FBbt_00045032,Superior Intermediate Protocerebrum,SIP,NaN,"[498, 129, 227]",78c679
1,2,VFB_00050003,FBbt_00007719,Tritocerebrum dorsal Right,TRd R,NaN,"[602, 409, 231]",88419d
2,3,VFB_00050004,FBbt_00007704,VNC centrolateral Right,VNCcl R,NaN,"[611, 929, 261]",389b64
3,4,VFB_00050005,FBbt_00015028,Mandibula centrolateral Right,MDcl R,NaN,"[638, 450, 254]",ce1256
4,5,VFB_00050006,FBbt_00015035,Maxilla centrolateral Right,MXcl R,NaN,"[642, 484, 255]",e7298a
5,6,VFB_00050007,FBbt_00015021,Labium centrolateral Right,LBcl R,NaN,"[647, 550, 253]",ce1256
6,7,VFB_00050008,FBbt_00015014,Thoracic Segment 1 centrolateral Right,T1cl R,NaN,"[633, 637, 253]",41ab5d
7,8,VFB_00050009,FBbt_00015000,Thoracic Segment 2 centrolateral Right,T2cl R,NaN,"[618, 749, 255]",238443
8,9,VFB_00050010,FBbt_00015007,Thoracic Segment 3 centrolateral Right,T3cl R,NaN,"[605, 881, 256]",41ab5d
9,10,VFB_00050011,FBbt_00015042,Abdominal Segment 1 centrolateral Right,A1cl R,NaN,"[594, 991, 257]",b9563e
10,11,VFB_00050012,FBbt_00015049,Abdominal Segment 2 centrolateral Right,A2cl R,NaN,"[590, 1080, 257]",cb6d4f
11,12,VFB_00050013,FBbt_00015056,Abdominal Segment 3 centrolateral Right,A3cl R,NaN,"[589, 1164, 260]",b9563e
12,13,VFB_00050014,FBbt_00015063,Abdominal Segment 4 centrolateral Right,A4cl R,NaN,"[588, 1243, 267]",cb6d4f
13,14,VFB_00050015,FBbt_00015070,Abdominal Segment 5 centrolateral Right,A5cl R,NaN,"[589, 1332, 275]",b9563e
14,15,VFB_00050016,FBbt_00015077,Abdominal Segment 6 centrolateral Right,A6cl R,NaN,"[589, 1415, 282]",cb6d4f
15,16,VFB_00050017,FBbt_00015084,Abdominal Segment 7 centrolateral Right,A7cl R,NaN,"[588, 1490, 294]",b9563e
16,17,VFB_00050018,FBbt_00015091,Abdominal Segment 8 centrolateral Right,A8cl R,NaN,"[585, 1547, 306]",cb6d4f
17,18,VFB_00050019,FBbt_00007066,Superior Medial Protocerebrum posterior,SMPp,NaN,"[499, 136, 215]",86a76f
18,19,VFB_00050020,FBbt_00007065,Superior Medial Protocerebrum anterior,SMPa,NaN,"[504, 143, 259]",c7e7b2
19,20,VFB_00050021,FBbt_00111203,Superior Medial Protocerebrum,SMP,NaN,"[500, 137, 220]",addd8e
20,21,VFB_00050022,FBbt_00111207,Fan-shaped Body Primoridum,prFB,NaN,"[494, 210, 230]",646464
21,22,VFB_00050023,FBbt_00007704,VNC centrolateral Left,VNCcl L,NaN,"[369, 912, 260]",389b64
22,23,VFB_00050024,FBbt_00015028,Mandibula centrolateral Left,MDcl L,NaN,"[308, 451, 258]",ce1256
23,24,VFB_00050025,FBbt_00015035,Maxilla centrolateral Left,MXcl L,NaN,"[308, 486, 254]",e7298a
24,25,VFB_00050026,FBbt_00015021,Labium centrolateral Left,LBcl L,NaN,"[317, 549, 253]",ce1256
25,26,VFB_00050027,FBbt_00015014,Thoracic Segment 1 centrolateral Left,T1cl L,NaN,"[337, 639, 253]",41ab5d
26,27,VFB_00050028,FBbt_00015000,Thoracic Segment 2 centrolateral Left,T2cl L,NaN,"[357, 751, 255]",238443
27,28,VFB_00050029,FBbt_00015007,Thoracic Segment 3 centrolateral Left,T3cl L,NaN,"[375, 877, 255]",41ab5d
28,29,VFB_00050030,FBbt_00015042,Abdominal Segment 1 centrolateral Left,A1cl L,NaN,"[389, 988, 257]",b9563e
29,30,VFB_00050031,FBbt_00015049,Abdominal Segment 2 centrolateral Left,A2cl L,NaN,"[397, 1079, 257]",cb6d4f
...,...,...,...,...,...,...,...,...
225,226,VFB_00050227,FBbt_00015092,Abdominal Segment 8 centromedial Left,A8cm L,NaN,"[479, 1547, 306]",fe9929
226,227,VFB_00050228,FBbt_00007706,VNC ventromedial Left,VNCvm L,NaN,"[451, 901, 286]",5cb0cf
227,228,VFB_00050229,FBbt_00015033,Mandibula ventromedial Left,MDvm L,NaN,"[420, 416, 281]",f768a1
228,229,VFB_00050230,FBbt_00015040,Maxilla ventromedial Left,MXvm L,NaN,"[424, 465, 280]",fa9fb5
229,230,VFB_00050231,FBbt_00015026,Labium ventromedial Left,LBvm L,NaN,"[434, 535, 276]",f768a1
230,231,VFB_00050232,FBbt_00015018,Thoracic Segment 1 ventromedial Left,T1vm L,NaN,"[441, 641, 275]",74a9cf
231,232,VFB_00050233,FBbt_00015004,Thoracic Segment 2 ventromedial Left,T2vm L,NaN,"[447, 773, 274]",addd8e
232,233,VFB_00050234,FBbt_00015011,Thoracic Segment 3 ventromedial Left,T3vm L,NaN,"[452, 896, 275]",74a9cf
233,234,VFB_00050235,FBbt_00015047,Abdominal Segment 1 ventromedial Left,A1vm L,NaN,"[456, 1001, 278]",fec44f
234,235,VFB_00050236,FBbt_00015054,Abdominal Segment 2 ventromedial Left,A2vm L,NaN,"[465, 1092, 281]",fee391
235,236,VFB_00050237,FBbt_00015061,Abdominal Segment 3 ventromedial Left,A3vm L,NaN,"[468, 1175, 287]",fec44f
236,237,VFB_00050238,FBbt_00015068,Abdominal Segment 4 ventromedial Left,A4vm L,NaN,"[470, 1254, 293]",fee391
237,238,VFB_00050239,FBbt_00015075,Abdominal Segment 5 ventromedial Left,A5vm L,NaN,"[472, 1330, 299]",fec44f
238,239,VFB_00050240,FBbt_00015082,Abdominal Segment 6 ventromedial Left,A6vm L,NaN,"[473, 1410, 308]",fee391
239,240,VFB_00050241,FBbt_00015089,Abdominal Segment 7 ventromedial Left,A7vm L,NaN,"[477, 1484, 317]",fec44f
240,241,VFB_00050242,FBbt_00015096,Abdominal Segment 8 ventromedial Left,A8vm L,NaN,"[482, 1551, 325]",fee391
241,242,VFB_00050243,FBbt_00007717,Tritocerebrum central Left,TRc L,NaN,"[325, 415, 252]",8c6bb1
242,243,VFB_00050244,FBbt_00007715,Abdominal Segment 9 ventral Right,A9v R,NaN,"[545, 1603, 290]",993404
243,244,VFB_00050245,FBbt_00110187,Peduncle,PED,NaN,"[479, 212, 200]",bd0026
244,245,VFB_00050246,FBbt_00110188,Medial Lobe,ML,NaN,"[494, 192, 253]",c80e0e
245,246,VFB_00050247,FBbt_00007191,Calyx,CX,NaN,"[491, 172, 145]",800026
246,247,VFB_00050248,FBbt_00110189,Vertical Lobe,VL,NaN,"[495, 107, 238]",ffbb63
247,248,VFB_00050249,FBbt_00110186,Spur,SPU,NaN,"[495, 178, 250]",e31a1c
248,249,VFB_00050250,FBbt_00011929,Mushroom Body,MB,NaN,"[490, 174, 198]",fd8d3c
249,250,VFB_00050252,FBbt_00007712,Thoracic Segment 2 Leg Neuropil Left,T2Leg L,NaN,"[331, 783, 271]",c85d68
250,251,VFB_00050253,FBbt_00110190,Lateral Appendix of the Medial Lobe,LAML,NaN,"[501, 155, 271]",d6d6d6
251,252,VFB_00050254,FBbt_00007716,Abdominal Segment 9 centro Left,A9c L,NaN,"[465, 1610, 311]",ec7014
252,253,VFB_00050255,FBbt_00007716,Abdominal Segment 9 centro Right,A9c R,NaN,"[547, 1607, 311]",de6c19
253,254,VFB_00050256,FBbt_00007712,Thoracic Segment 2 Leg Neuropil Right,T2Leg R,NaN,"[655, 778, 271]",c85d68
254,255,VFB_00050257,FBbt_00007720,Tritocerebrum ventral Left,TRv L,NaN,"[359, 351, 289]",8c96c6

In [14]:
ltd = []
for i,r in mapping_table.iterrows():
    LR = ''
    if re.match('.+Left', r.Name): LR = "left "
    if re.match('.+Right', r.Name): LR = "right "
    class_name = fbbt.label(re.sub('_', ':', r.Class_ID))
    label_core = re.sub('(embryonic/larval |larval |segment )', '', class_name)
    d = {}
    d['label'] = LR + label_core + ' on L3 CNS template, Wood2018' # Need L/R!
    d['synonyms'] = [r.Abbreviation, r.Name]
    d['Index'] = r.Index
    d['Anatomical_type'] = r.Class_ID
    d['centre'] = yaml.load(r.Centre)
    d['VFB_id'] = ''
    ltd.append(d)
    
loading_table = pd.DataFrame.from_records(ltd)
loading_table

,Anatomical_type,Index,VFB_id,centre,label,synonyms
0,FBbt_00045032,1,,"[498, 129, 227]",superior intermediate protocerebrum on L3 CNS ...,"[SIP, Superior Intermediate Protocerebrum]"
1,FBbt_00007719,2,,"[602, 409, 231]",right dorsomedial neuropil of tritocerebrum on...,"[TRd R, Tritocerebrum dorsal Right]"
2,FBbt_00007704,3,,"[611, 929, 261]",right centrolateral subdivision of ventral ner...,"[VNCcl R, VNC centrolateral Right]"
3,FBbt_00015028,4,,"[638, 450, 254]",right centrolateral neuropil of mandibular seg...,"[MDcl R, Mandibula centrolateral Right]"
4,FBbt_00015035,5,,"[642, 484, 255]",right centrolateral neuropil of maxillary segm...,"[MXcl R, Maxilla centrolateral Right]"
5,FBbt_00015021,6,,"[647, 550, 253]",right centrolateral neuropil of labial segment...,"[LBcl R, Labium centrolateral Right]"
6,FBbt_00015014,7,,"[633, 637, 253]",right centrolateral neuropil of T1 on L3 CNS t...,"[T1cl R, Thoracic Segment 1 centrolateral Right]"
7,FBbt_00015000,8,,"[618, 749, 255]",right centrolateral neuropil of T2 on L3 CNS t...,"[T2cl R, Thoracic Segment 2 centrolateral Right]"
8,FBbt_00015007,9,,"[605, 881, 256]",right centrolateral neuropil of T3 on L3 CNS t...,"[T3cl R, Thoracic Segment 3 centrolateral Right]"
9,FBbt_00015042,10,,"[594, 991, 257]",right centrolateral neuropil of A1 on L3 CNS t...,"[A1cl R, Abdominal Segment 1 centrolateral Right]"
10,FBbt_00015049,11,,"[590, 1080, 257]",right centrolateral neuropil of A2 on L3 CNS t...,"[A2cl R, Abdominal Segment 2 centrolateral Right]"
11,FBbt_00015056,12,,"[589, 1164, 260]",right centrolateral neuropil of A3 on L3 CNS t...,"[A3cl R, Abdominal Segment 3 centrolateral Right]"
12,FBbt_00015063,13,,"[588, 1243, 267]",right centrolateral neuropil of A4 on L3 CNS t...,"[A4cl R, Abdominal Segment 4 centrolateral Right]"
13,FBbt_00015070,14,,"[589, 1332, 275]",right centrolateral neuropil of A5 on L3 CNS t...,"[A5cl R, Abdominal Segment 5 centrolateral Right]"
14,FBbt_00015077,15,,"[589, 1415, 282]",right centrolateral neuropil of A6 on L3 CNS t...,"[A6cl R, Abdominal Segment 6 centrolateral Right]"
15,FBbt_00015084,16,,"[588, 1490, 294]",right centrolateral neuropil of A7 on L3 CNS t...,"[A7cl R, Abdominal Segment 7 centrolateral Right]"
16,FBbt_00015091,17,,"[585, 1547, 306]",right centrolateral neuropil of A8 on L3 CNS t...,"[A8cl R, Abdominal Segment 8 centrolateral Right]"
17,FBbt_00007066,18,,"[499, 136, 215]",posterior superior medial protocerebrum on L3 ...,"[SMPp, Superior Medial Protocerebrum posterior]"
18,FBbt_00007065,19,,"[504, 143, 259]",anterior superior medial protocerebrum on L3 C...,"[SMPa, Superior Medial Protocerebrum anterior]"
19,FBbt_00111203,20,,"[500, 137, 220]",superior medial protocerebrum on L3 CNS templa...,"[SMP, Superior Medial Protocerebrum]"
20,FBbt_00111207,21,,"[494, 210, 230]",fan-shaped body - primordial on L3 CNS templat...,"[prFB, Fan-shaped Body Primoridum]"
21,FBbt_00007704,22,,"[369, 912, 260]",left centrolateral subdivision of ventral nerv...,"[VNCcl L, VNC centrolateral Left]"
22,FBbt_00015028,23,,"[308, 451, 258]",left centrolateral neuropil of mandibular segm...,"[MDcl L, Mandibula centrolateral Left]"
23,FBbt_00015035,24,,"[308, 486, 254]",left centrolateral neuropil of maxillary segme...,"[MXcl L, Maxilla centrolateral Left]"
24,FBbt_00015021,25,,"[317, 549, 253]",left centrolateral neuropil of labial segment ...,"[LBcl L, Labium centrolateral Left]"
25,FBbt_00015014,26,,"[337, 639, 253]",left centrolateral neuropil of T1 on L3 CNS te...,"[T1cl L, Thoracic Segment 1 centrolateral Left]"
26,FBbt_00015000,27,,"[357, 751, 255]",left centrolateral neuropil of T2 on L3 CNS te...,"[T2cl L, Thoracic Segment 2 centrolateral Left]"
27,FBbt_00015007,28,,"[375, 877, 255]",left centrolateral neuropil of T3 on L3 CNS te...,"[T3cl L, Thoracic Segment 3 centrolateral Left]"
28,FBbt_00015042,29,,"[389, 988, 257]",left centrolateral neuropil of A1 on L3 CNS te...,"[A1cl L, Abdominal Segment 1 centrolateral Left]"
29,FBbt_00015049,30,,"[397, 1079, 257]",left centrolateral neuropil of A2 on L3 CNS te...,"[A2cl L, Abdominal Segment 2 centrolateral Left]"
...,...,...,...,...,...,...
225,FBbt_00015092,226,,"[479, 1547, 306]",left centromedial neuropil of A8 on L3 CNS tem...,"[A8cm L, Abdominal Segment 8 centromedial Left]"
226,FBbt_00007706,227,,"[451, 901, 286]",left ventromedial subdivision of ventral nerve...,"[VNCvm L, VNC ventromedial Left]"
227,FBbt_00015033,228,,"[420, 416, 281]",left ventromedial neuropil of mandibular segme...,"[MDvm L, Mandibula ventromedial Left]"
228,FBbt_00015040,229,,"[424, 465, 280]",left ventromedial neuropil of maxillary segmen...,"[MXvm L, Maxilla ventromedial Left]"
229,FBbt_00015026,230,,"[434, 535, 276]",left ventromedial neuropil of labial segment o...,"[LBvm L, Labium ventromedial Left]"
230,FBbt_00015018,231,,"[441, 641, 275]",left ventrolateral neuropil of T1 on L3 CNS te...,"[T1vm L, Thoracic Segment 1 ventromedial Left]"
231,FBbt_00015004,232,,"[447, 773, 274]",left ventrolateral neuropil of T2 on L3 CNS te...,"[T2vm L, Thoracic Segment 2 ventromedial Left]"
232,FBbt_00015011,233,,"[452, 896, 275]",left ventrolateral neuropil of T3 on L3 CNS te...,"[T3vm L, Thoracic Segment 3 ventromedial Left]"
233,FBbt_00015047,234,,"[456, 1001, 278]",left ventromedial neuropil of A1 on L3 CNS tem...,"[A1vm L, Abdominal Segment 1 ventromedial Left]"
234,FBbt_00015054,235,,"[465, 1092, 281]",left ventromedial neuropil of A2 on L3 CNS tem...,"[A2vm L, Abdominal Segment 2 ventromedial Left]"
235,FBbt_00015061,236,,"[468, 1175, 287]",left ventromedial neuropil of A3 on L3 CNS tem...,"[A3vm L, Abdominal Segment 3 ventromedial Left]"
236,FBbt_00015068,237,,"[470, 1254, 293]",left ventromedial neuropil of A4 on L3 CNS tem...,"[A4vm L, Abdominal Segment 4 ventromedial Left]"
237,FBbt_00015075,238,,"[472, 1330, 299]",left ventromedial neuropil of A5 on L3 CNS tem...,"[A5vm L, Abdominal Segment 5 ventromedial Left]"
238,FBbt_00015082,239,,"[473, 1410, 308]",left ventromedial neuropil of A6 on L3 CNS tem...,"[A6vm L, Abdominal Segment 6 ventromedial Left]"
239,FBbt_00015089,240,,"[477, 1484, 317]",left ventromedial neuropil of A7 on L3 CNS tem...,"[A7vm L, Abdominal Segment 7 ventromedial Left]"
240,FBbt_00015096,241,,"[482, 1551, 325]",left ventromedial neuropil of A8 on L3 CNS tem...,"[A8vm L, Abdominal Segment 8 ventromedial Left]"
241,FBbt_00007717,242,,"[325, 415, 252]",left central neuropil of tritocerebrum on L3 C...,"[TRc L, Tritocerebrum central Left]"
242,FBbt_00007715,243,,"[545, 1603, 290]",right ventral neuropil of A9 on L3 CNS templat...,"[A9v R, Abdominal Segment 9 ventral Right]"
243,FBbt_00110187,244,,"[479, 212, 200]",pedunculus of mushroom body on L3 CNS template...,"[PED, Peduncle]"
244,FBbt_00110188,245,,"[494, 192, 253]",medial lobe of mushroom body on L3 CNS templat...,"[ML, Medial Lobe]"
245,FBbt_00007191,246,,"[491, 172, 145]","calyx of mushroom body on L3 CNS template, Woo...","[CX, Calyx]"
246,FBbt_00110189,247,,"[495, 107, 238]",vertical lobe of mushroom body on L3 CNS templ...,"[VL, Vertical Lobe]"
247,FBbt_00110186,248,,"[495, 178, 250]","spur of mushroom body on L3 CNS template, Wood...","[SPU, Spur]"
248,FBbt_00011929,249,,"[490, 174, 198]","mushroom body on L3 CNS template, Wood2018","[MB, Mushroom Body]"
249,FBbt_00007712,250,,"[331, 783, 271]","left T2 leg neuropil on L3 CNS template, Wood2018","[T2Leg L, Thoracic Segment 2 Leg Neuropil Left]"
250,FBbt_00110190,251,,"[501, 155, 271]",lateral appendix of mushroom body on L3 CNS te...,"[LAML, Lateral Appendix of the Medial Lobe]"
251,FBbt_00007716,252,,"[465, 1610, 311]",left central neuropil of A9 on L3 CNS template...,"[A9c L, Abdominal Segment 9 centro Left]"
252,FBbt_00007716,253,,"[547, 1607, 311]",right central neuropil of A9 on L3 CNS templat...,"[A9c R, Abdominal Segment 9 centro Right]"
253,FBbt_00007712,254,,"[655, 778, 271]","right T2 leg neuropil on L3 CNS template, Wood...","[T2Leg R, Thoracic Segment 2 Leg Neuropil Right]"
254,FBbt_00007720,255,,"[359, 351, 289]",left ventromedial neuropil of tritocerebrum on...,"[TRv L, Tritocerebrum ventral Left]"

In [15]:
lt_out = loading_table.copy()

for k,r in lt_out.iterrows():
    synstring = "|".join(r.synonyms)
    lt.out[k, "synonyms"] = synstring
    cstring = "|".join([str(x) for x in r.centre])
    lt_out.at[k, "centre"] = cstring

lt_out.to_csv("loading_table.tsv", sep = "\t")

In [4]:
for i,r in loading_table.iterrows():

    anatomy_attributes = {}
    anatomy_attributes['synonyms'] = r.synonyms
    iris = kbw.add_anatomy_image_set(dataset = "WoodHartenstein2018",
                                     index = r.Index,
                                     imaging_type = "computer graphic", 
                                     label = r.label,
                                     start = 50002, 
                                     template = 'VFBc_00049000', 
                                     anatomical_type=r.Anatomical_type,
                                     anatomy_attributes=anatomy_attributes,
                                     center=r.centre       
                                     )
    r.VFB_id = iris['anatomy']
loading_table.to_csv("Domains_report.tsv")

,Anatomical_type,Index,VFB_id,centre,label,synonyms
0,FBbt_00045032,1,,"[498, 129, 227]",superior intermediate protocerebrum on L3 CNS ...,"[SIP, Superior Intermediate Protocerebrum]"
1,FBbt_00007719,2,,"[602, 409, 231]",right dorsomedial neuropil of tritocerebrum on...,"[TRd R, Tritocerebrum dorsal Right]"
2,FBbt_00007704,3,,"[611, 929, 261]",right centrolateral subdivision of ventral ner...,"[VNCcl R, VNC centrolateral Right]"
3,FBbt_00015028,4,,"[638, 450, 254]",right centrolateral neuropil of mandibular seg...,"[MDcl R, Mandibula centrolateral Right]"
4,FBbt_00015035,5,,"[642, 484, 255]",right centrolateral neuropil of maxillary segm...,"[MXcl R, Maxilla centrolateral Right]"
5,FBbt_00015021,6,,"[647, 550, 253]",right centrolateral neuropil of labial segment...,"[LBcl R, Labium centrolateral Right]"
6,FBbt_00015014,7,,"[633, 637, 253]",right centrolateral neuropil of T1 on L3 CNS t...,"[T1cl R, Thoracic Segment 1 centrolateral Right]"
7,FBbt_00015000,8,,"[618, 749, 255]",right centrolateral neuropil of T2 on L3 CNS t...,"[T2cl R, Thoracic Segment 2 centrolateral Right]"
8,FBbt_00015007,9,,"[605, 881, 256]",right centrolateral neuropil of T3 on L3 CNS t...,"[T3cl R, Thoracic Segment 3 centrolateral Right]"
9,FBbt_00015042,10,,"[594, 991, 257]",right centrolateral neuropil of A1 on L3 CNS t...,"[A1cl R, Abdominal Segment 1 centrolateral Right]"
10,FBbt_00015049,11,,"[590, 1080, 257]",right centrolateral neuropil of A2 on L3 CNS t...,"[A2cl R, Abdominal Segment 2 centrolateral Right]"
11,FBbt_00015056,12,,"[589, 1164, 260]",right centrolateral neuropil of A3 on L3 CNS t...,"[A3cl R, Abdominal Segment 3 centrolateral Right]"
12,FBbt_00015063,13,,"[588, 1243, 267]",right centrolateral neuropil of A4 on L3 CNS t...,"[A4cl R, Abdominal Segment 4 centrolateral Right]"
13,FBbt_00015070,14,,"[589, 1332, 275]",right centrolateral neuropil of A5 on L3 CNS t...,"[A5cl R, Abdominal Segment 5 centrolateral Right]"
14,FBbt_00015077,15,,"[589, 1415, 282]",right centrolateral neuropil of A6 on L3 CNS t...,"[A6cl R, Abdominal Segment 6 centrolateral Right]"
15,FBbt_00015084,16,,"[588, 1490, 294]",right centrolateral neuropil of A7 on L3 CNS t...,"[A7cl R, Abdominal Segment 7 centrolateral Right]"
16,FBbt_00015091,17,,"[585, 1547, 306]",right centrolateral neuropil of A8 on L3 CNS t...,"[A8cl R, Abdominal Segment 8 centrolateral Right]"
17,FBbt_00007066,18,,"[499, 136, 215]",posterior superior medial protocerebrum on L3 ...,"[SMPp, Superior Medial Protocerebrum posterior]"
18,FBbt_00007065,19,,"[504, 143, 259]",anterior superior medial protocerebrum on L3 C...,"[SMPa, Superior Medial Protocerebrum anterior]"
19,FBbt_00111203,20,,"[500, 137, 220]",superior medial protocerebrum on L3 CNS templa...,"[SMP, Superior Medial Protocerebrum]"
20,FBbt_00111207,21,,"[494, 210, 230]",fan-shaped body - primordial on L3 CNS templat...,"[prFB, Fan-shaped Body Primoridum]"
21,FBbt_00007704,22,,"[369, 912, 260]",left centrolateral subdivision of ventral nerv...,"[VNCcl L, VNC centrolateral Left]"
22,FBbt_00015028,23,,"[308, 451, 258]",left centrolateral neuropil of mandibular segm...,"[MDcl L, Mandibula centrolateral Left]"
23,FBbt_00015035,24,,"[308, 486, 254]",left centrolateral neuropil of maxillary segme...,"[MXcl L, Maxilla centrolateral Left]"
24,FBbt_00015021,25,,"[317, 549, 253]",left centrolateral neuropil of labial segment ...,"[LBcl L, Labium centrolateral Left]"
25,FBbt_00015014,26,,"[337, 639, 253]",left centrolateral neuropil of T1 on L3 CNS te...,"[T1cl L, Thoracic Segment 1 centrolateral Left]"
26,FBbt_00015000,27,,"[357, 751, 255]",left centrolateral neuropil of T2 on L3 CNS te...,"[T2cl L, Thoracic Segment 2 centrolateral Left]"
27,FBbt_00015007,28,,"[375, 877, 255]",left centrolateral neuropil of T3 on L3 CNS te...,"[T3cl L, Thoracic Segment 3 centrolateral Left]"
28,FBbt_00015042,29,,"[389, 988, 257]",left centrolateral neuropil of A1 on L3 CNS te...,"[A1cl L, Abdominal Segment 1 centrolateral Left]"
29,FBbt_00015049,30,,"[397, 1079, 257]",left centrolateral neuropil of A2 on L3 CNS te...,"[A2cl L, Abdominal Segment 2 centrolateral Left]"
...,...,...,...,...,...,...
225,FBbt_00015092,226,,"[479, 1547, 306]",left centromedial neuropil of A8 on L3 CNS tem...,"[A8cm L, Abdominal Segment 8 centromedial Left]"
226,FBbt_00007706,227,,"[451, 901, 286]",left ventromedial subdivision of ventral nerve...,"[VNCvm L, VNC ventromedial Left]"
227,FBbt_00015033,228,,"[420, 416, 281]",left ventromedial neuropil of mandibular segme...,"[MDvm L, Mandibula ventromedial Left]"
228,FBbt_00015040,229,,"[424, 465, 280]",left ventromedial neuropil of maxillary segmen...,"[MXvm L, Maxilla ventromedial Left]"
229,FBbt_00015026,230,,"[434, 535, 276]",left ventromedial neuropil of labial segment o...,"[LBvm L, Labium ventromedial Left]"
230,FBbt_00015018,231,,"[441, 641, 275]",left ventrolateral neuropil of T1 on L3 CNS te...,"[T1vm L, Thoracic Segment 1 ventromedial Left]"
231,FBbt_00015004,232,,"[447, 773, 274]",left ventrolateral neuropil of T2 on L3 CNS te...,"[T2vm L, Thoracic Segment 2 ventromedial Left]"
232,FBbt_00015011,233,,"[452, 896, 275]",left ventrolateral neuropil of T3 on L3 CNS te...,"[T3vm L, Thoracic Segment 3 ventromedial Left]"
233,FBbt_00015047,234,,"[456, 1001, 278]",left ventromedial neuropil of A1 on L3 CNS tem...,"[A1vm L, Abdominal Segment 1 ventromedial Left]"
234,FBbt_00015054,235,,"[465, 1092, 281]",left ventromedial neuropil of A2 on L3 CNS tem...,"[A2vm L, Abdominal Segment 2 ventromedial Left]"
235,FBbt_00015061,236,,"[468, 1175, 287]",left ventromedial neuropil of A3 on L3 CNS tem...,"[A3vm L, Abdominal Segment 3 ventromedial Left]"
236,FBbt_00015068,237,,"[470, 1254, 293]",left ventromedial neuropil of A4 on L3 CNS tem...,"[A4vm L, Abdominal Segment 4 ventromedial Left]"
237,FBbt_00015075,238,,"[472, 1330, 299]",left ventromedial neuropil of A5 on L3 CNS tem...,"[A5vm L, Abdominal Segment 5 ventromedial Left]"
238,FBbt_00015082,239,,"[473, 1410, 308]",left ventromedial neuropil of A6 on L3 CNS tem...,"[A6vm L, Abdominal Segment 6 ventromedial Left]"
239,FBbt_00015089,240,,"[477, 1484, 317]",left ventromedial neuropil of A7 on L3 CNS tem...,"[A7vm L, Abdominal Segment 7 ventromedial Left]"
240,FBbt_00015096,241,,"[482, 1551, 325]",left ventromedial neuropil of A8 on L3 CNS tem...,"[A8vm L, Abdominal Segment 8 ventromedial Left]"
241,FBbt_00007717,242,,"[325, 415, 252]",left central neuropil of tritocerebrum on L3 C...,"[TRc L, Tritocerebrum central Left]"
242,FBbt_00007715,243,,"[545, 1603, 290]",right ventral neuropil of A9 on L3 CNS templat...,"[A9v R, Abdominal Segment 9 ventral Right]"
243,FBbt_00110187,244,,"[479, 212, 200]",pedunculus of mushroom body on L3 CNS template...,"[PED, Peduncle]"
244,FBbt_00110188,245,,"[494, 192, 253]",medial lobe of mushroom body on L3 CNS templat...,"[ML, Medial Lobe]"
245,FBbt_00007191,246,,"[491, 172, 145]","calyx of mushroom body on L3 CNS template, Woo...","[CX, Calyx]"
246,FBbt_00110189,247,,"[495, 107, 238]",vertical lobe of mushroom body on L3 CNS templ...,"[VL, Vertical Lobe]"
247,FBbt_00110186,248,,"[495, 178, 250]","spur of mushroom body on L3 CNS template, Wood...","[SPU, Spur]"
248,FBbt_00011929,249,,"[490, 174, 198]","mushroom body on L3 CNS template, Wood2018","[MB, Mushroom Body]"
249,FBbt_00007712,250,,"[331, 783, 271]","left T2 leg neuropil on L3 CNS template, Wood2018","[T2Leg L, Thoracic Segment 2 Leg Neuropil Left]"
250,FBbt_00110190,251,,"[501, 155, 271]",lateral appendix of mushroom body on L3 CNS te...,"[LAML, Lateral Appendix of the Medial Lobe]"
251,FBbt_00007716,252,,"[465, 1610, 311]",left central neuropil of A9 on L3 CNS template...,"[A9c L, Abdominal Segment 9 centro Left]"
252,FBbt_00007716,253,,"[547, 1607, 311]",right central neuropil of A9 on L3 CNS templat...,"[A9c R, Abdominal Segment 9 centro Right]"
253,FBbt_00007712,254,,"[655, 778, 271]","right T2 leg neuropil on L3 CNS template, Wood...","[T2Leg R, Thoracic Segment 2 Leg Neuropil Right]"
254,FBbt_00007720,255,,"[359, 351, 289]",left ventromedial neuropil of tritocerebrum on...,"[TRv L, Tritocerebrum ventral Left]"

,Anatomical_type,Index,VFB_id,centre,label,synonyms
0,FBbt_00045032,1.0,,498|129|227,superior intermediate protocerebrum on L3 CNS ...,SIP|Superior Intermediate Protocerebrum
1,FBbt_00007719,2.0,,4|9|8|||1|2|9|||2|2|7,right dorsomedial neuropil of tritocerebrum on...,S|I|P|||S|u|p|e|r|i|o|r| |I|n|t|e|r|m|e|d|i|a|...
2,FBbt_00007704,3.0,,6|0|2|||4|0|9|||2|3|1,right centrolateral subdivision of ventral ner...,T|R|d| |R|||T|r|i|t|o|c|e|r|e|b|r|u|m| |d|o|r|...
3,FBbt_00015028,4.0,,6|1|1|||9|2|9|||2|6|1,right centrolateral neuropil of mandibular seg...,V|N|C|c|l| |R|||V|N|C| |c|e|n|t|r|o|l|a|t|e|r|...
4,FBbt_00015035,5.0,,6|3|8|||4|5|0|||2|5|4,right centrolateral neuropil of maxillary segm...,M|D|c|l| |R|||M|a|n|d|i|b|u|l|a| |c|e|n|t|r|o|...
5,FBbt_00015021,6.0,,6|4|2|||4|8|4|||2|5|5,right centrolateral neuropil of labial segment...,M|X|c|l| |R|||M|a|x|i|l|l|a| |c|e|n|t|r|o|l|a|...
6,FBbt_00015014,7.0,,6|4|7|||5|5|0|||2|5|3,right centrolateral neuropil of T1 on L3 CNS t...,L|B|c|l| |R|||L|a|b|i|u|m| |c|e|n|t|r|o|l|a|t|...
7,FBbt_00015000,8.0,,6|3|3|||6|3|7|||2|5|3,right centrolateral neuropil of T2 on L3 CNS t...,T|1|c|l| |R|||T|h|o|r|a|c|i|c| |S|e|g|m|e|n|t|...
8,FBbt_00015007,9.0,,6|1|8|||7|4|9|||2|5|5,right centrolateral neuropil of T3 on L3 CNS t...,T|2|c|l| |R|||T|h|o|r|a|c|i|c| |S|e|g|m|e|n|t|...
9,FBbt_00015042,10.0,,6|0|5|||8|8|1|||2|5|6,right centrolateral neuropil of A1 on L3 CNS t...,T|3|c|l| |R|||T|h|o|r|a|c|i|c| |S|e|g|m|e|n|t|...
10,FBbt_00015049,11.0,,5|9|4|||9|9|1|||2|5|7,right centrolateral neuropil of A2 on L3 CNS t...,A|1|c|l| |R|||A|b|d|o|m|i|n|a|l| |S|e|g|m|e|n|...
11,FBbt_00015056,12.0,,5|9|0|||1|0|8|0|||2|5|7,right centrolateral neuropil of A3 on L3 CNS t...,A|2|c|l| |R|||A|b|d|o|m|i|n|a|l| |S|e|g|m|e|n|...
12,FBbt_00015063,13.0,,5|8|9|||1|1|6|4|||2|6|0,right centrolateral neuropil of A4 on L3 CNS t...,A|3|c|l| |R|||A|b|d|o|m|i|n|a|l| |S|e|g|m|e|n|...
13,FBbt_00015070,14.0,,5|8|8|||1|2|4|3|||2|6|7,right centrolateral neuropil of A5 on L3 CNS t...,A|4|c|l| |R|||A|b|d|o|m|i|n|a|l| |S|e|g|m|e|n|...
14,FBbt_00015077,15.0,,5|8|9|||1|3|3|2|||2|7|5,right centrolateral neuropil of A6 on L3 CNS t...,A|5|c|l| |R|||A|b|d|o|m|i|n|a|l| |S|e|g|m|e|n|...
15,FBbt_00015084,16.0,,5|8|9|||1|4|1|5|||2|8|2,right centrolateral neuropil of A7 on L3 CNS t...,A|6|c|l| |R|||A|b|d|o|m|i|n|a|l| |S|e|g|m|e|n|...
16,FBbt_00015091,17.0,,5|8|8|||1|4|9|0|||2|9|4,right centrolateral neuropil of A8 on L3 CNS t...,A|7|c|l| |R|||A|b|d|o|m|i|n|a|l| |S|e|g|m|e|n|...
17,FBbt_00007066,18.0,,5|8|5|||1|5|4|7|||3|0|6,posterior superior medial protocerebrum on L3 ...,A|8|c|l| |R|||A|b|d|o|m|i|n|a|l| |S|e|g|m|e|n|...
18,FBbt_00007065,19.0,,4|9|9|||1|3|6|||2|1|5,anterior superior medial protocerebrum on L3 C...,S|M|P|p|||S|u|p|e|r|i|o|r| |M|e|d|i|a|l| |P|r|...
19,FBbt_00111203,20.0,,5|0|4|||1|4|3|||2|5|9,superior medial protocerebrum on L3 CNS templa...,S|M|P|a|||S|u|p|e|r|i|o|r| |M|e|d|i|a|l| |P|r|...
20,FBbt_00111207,21.0,,5|0|0|||1|3|7|||2|2|0,fan-shaped body - primordial on L3 CNS templat...,S|M|P|||S|u|p|e|r|i|o|r| |M|e|d|i|a|l| |P|r|o|...
21,FBbt_00007704,22.0,,4|9|4|||2|1|0|||2|3|0,left centrolateral subdivision of ventral nerv...,p|r|F|B|||F|a|n|-|s|h|a|p|e|d| |B|o|d|y| |P|r|...
22,FBbt_00015028,23.0,,3|6|9|||9|1|2|||2|6|0,left centrolateral neuropil of mandibular segm...,V|N|C|c|l| |L|||V|N|C| |c|e|n|t|r|o|l|a|t|e|r|...
23,FBbt_00015035,24.0,,3|0|8|||4|5|1|||2|5|8,left centrolateral neuropil of maxillary segme...,M|D|c|l| |L|||M|a|n|d|i|b|u|l|a| |c|e|n|t|r|o|...
24,FBbt_00015021,25.0,,3|0|8|||4|8|6|||2|5|4,left centrolateral neuropil of labial segment ...,M|X|c|l| |L|||M|a|x|i|l|l|a| |c|e|n|t|r|o|l|a|...
25,FBbt_00015014,26.0,,3|1|7|||5|4|9|||2|5|3,left centrolateral neuropil of T1 on L3 CNS te...,L|B|c|l| |L|||L|a|b|i|u|m| |c|e|n|t|r|o|l|a|t|...
26,FBbt_00015000,27.0,,3|3|7|||6|3|9|||2|5|3,left centrolateral neuropil of T2 on L3 CNS te...,T|1|c|l| |L|||T|h|o|r|a|c|i|c| |S|e|g|m|e|n|t|...
27,FBbt_00015007,28.0,,3|5|7|||7|5|1|||2|5|5,left centrolateral neuropil of T3 on L3 CNS te...,T|2|c|l| |L|||T|h|o|r|a|c|i|c| |S|e|g|m|e|n|t|...
28,FBbt_00015042,29.0,,3|7|5|||8|7|7|||2|5|5,left centrolateral neuropil of A1 on L3 CNS te...,T|3|c|l| |L|||T|h|o|r|a|c|i|c| |S|e|g|m|e|n|t|...
29,FBbt_00015049,30.0,,3|8|9|||9|8|8|||2|5|7,left centrolateral neuropil of A2 on L3 CNS te...,A|1|c|l| |L|||A|b|d|o|m|i|n|a|l| |S|e|g|m|e|n|...
...,...,...,...,...,...,...
226,FBbt_00007706,227.0,,4|7|9|||1|5|4|7|||3|0|6,left ventromedial subdivision of ventral nerve...,A|8|c|m| |L|||A|b|d|o|m|i|n|a|l| |S|e|g|m|e|n|...
227,FBbt_00015033,228.0,,4|5|1|||9|0|1|||2|8|6,left ventromedial neuropil of mandibular segme...,V|N|C|v|m| |L|||V|N|C| |v|e|n|t|r|o|m|e|d|i|a|...
228,FBbt_00015040,229.0,,4|2|0|||4|1|6|||2|8|1,left ventromedial neuropil of maxillary segmen...,M|D|v|m| |L|||M|a|n|d|i|b|u|l|a| |v|e|n|t|r|o|...
229,FBbt_00015026,230.0,,4|2|4|||4|6|5|||2|8|0,left ventromedial neuropil of labial segment o...,M|X|v|m| |L|||M|a|x|i|l|l|a| |v|e|n|t|r|o|m|e|...
230,FBbt_00015018,231.0,,4|3|4|||5|3|5|||2|7|6,left ventrolateral neuropil of T1 on L3 CNS te...,L|B|v|m| |L|||L|a|b|i|u|m| |v|e|n|t|r|o|m|e|d|...
231,FBbt_00015004,232.0,,4|4|1|||6|4|1|||2|7|5,left ventrolateral neuropil of T2 on L3 CNS te...,T|1|v|m| |L|||T|h|o|r|a|c|i|c| |S|e|g|m|e|n|t|...
232,FBbt_00015011,233.0,,4|4|7|||7|7|3|||2|7|4,left ventrolateral neuropil of T3 on L3 CNS te...,T|2|v|m| |L|||T|h|o|r|a|c|i|c| |S|e|g|m|e|n|t|...
233,FBbt_00015047,234.0,,4|5|2|||8|9|6|||2|7|5,left ventromedial neuropil of A1 on L3 CNS tem...,T|3|v|m| |L|||T|h|o|r|a|c|i|c| |S|e|g|m|e|n|t|...
234,FBbt_00015054,235.0,,4|5|6|||1|0|0|1|||2|7|8,left ventromedial neuropil of A2 on L3 CNS tem...,A|1|v|m| |L|||A|b|d|o|m|i|n|a|l| |S|e|g|m|e|n|...
235,FBbt_00015061,236.0,,4|6|5|||1|0|9|2|||2|8|1,left ventromedial neuropil of A3 on L3 CNS tem...,A|2|v|m| |L|||A|b|d|o|m|i|n|a|l| |S|e|g|m|e|n|...
236,FBbt_00015068,237.0,,4|6|8|||1|1|7|5|||2|8|7,left ventromedial neuropil of A4 on L3 CNS tem...,A|3|v|m| |L|||A|b|d|o|m|i|n|a|l| |S|e|g|m|e|n|...
237,FBbt_00015075,238.0,,4|7|0|||1|2|5|4|||2|9|3,left ventromedial neuropil of A5 on L3 CNS tem...,A|4|v|m| |L|||A|b|d|o|m|i|n|a|l| |S|e|g|m|e|n|...
238,FBbt_00015082,239.0,,4|7|2|||1|3|3|0|||2|9|9,left ventromedial neuropil of A6 on L3 CNS tem...,A|5|v|m| |L|||A|b|d|o|m|i|n|a|l| |S|e|g|m|e|n|...
239,FBbt_00015089,240.0,,4|7|3|||1|4|1|0|||3|0|8,left ventromedial neuropil of A7 on L3 CNS tem...,A|6|v|m| |L|||A|b|d|o|m|i|n|a|l| |S|e|g|m|e|n|...
240,FBbt_00015096,241.0,,4|7|7|||1|4|8|4|||3|1|7,left ventromedial neuropil of A8 on L3 CNS tem...,A|7|v|m| |L|||A|b|d|o|m|i|n|a|l| |S|e|g|m|e|n|...
241,FBbt_00007717,242.0,,4|8|2|||1|5|5|1|||3|2|5,left central neuropil of tritocerebrum on L3 C...,A|8|v|m| |L|||A|b|d|o|m|i|n|a|l| |S|e|g|m|e|n|...
242,FBbt_00007715,243.0,,3|2|5|||4|1|5|||2|5|2,right ventral neuropil of A9 on L3 CNS templat...,T|R|c| |L|||T|r|i|t|o|c|e|r|e|b|r|u|m| |c|e|n|...
243,FBbt_00110187,244.0,,5|4|5|||1|6|0|3|||2|9|0,pedunculus of mushroom body on L3 CNS template...,A|9|v| |R|||A|b|d|o|m|i|n|a|l| |S|e|g|m|e|n|t|...
244,FBbt_00110188,245.0,,4|7|9|||2|1|2|||2|0|0,medial lobe of mushroom body on L3 CNS templat...,P|E|D|||P|e|d|u|n|c|l|e
245,FBbt_00007191,246.0,,4|9|4|||1|9|2|||2|5|3,"calyx of mushroom body on L3 CNS template, Woo...",M|L|||M|e|d|i|a|l| |L|o|b|e
246,FBbt_00110189,247.0,,4|9|1|||1|7|2|||1|4|5,vertical lobe of mushroom body on L3 CNS templ...,C|X|||C|a|l|y|x
247,FBbt_00110186,248.0,,4|9|5|||1|0|7|||2|3|8,"spur of mushroom body on L3 CNS template, Wood...",V|L|||V|e|r|t|i|c|a|l| |L|o|b|e
248,FBbt_00011929,249.0,,4|9|5|||1|7|8|||2|5|0,"mushroom body on L3 CNS template, Wood2018",S|P|U|||S|p|u|r
249,FBbt_00007712,250.0,,4|9|0|||1|7|4|||1|9|8,"left T2 leg neuropil on L3 CNS template, Wood2018",M|B|||M|u|s|h|r|o|o|m| |B|o|d|y
250,FBbt_00110190,251.0,,3|3|1|||7|8|3|||2|7|1,lateral appendix of mushroom body on L3 CNS te...,T|2|L|e|g| |L|||T|h|o|r|a|c|i|c| |S|e|g|m|e|n|...
251,FBbt_00007716,252.0,,5|0|1|||1|5|5|||2|7|1,left central neuropil of A9 on L3 CNS template...,L|A|M|L|||L|a|t|e|r|a|l| |A|p|p|e|n|d|i|x| |o|...
252,FBbt_00007716,253.0,,4|6|5|||1|6|1|0|||3|1|1,right central neuropil of A9 on L3 CNS templat...,A|9|c| |L|||A|b|d|o|m|i|n|a|l| |S|e|g|m|e|n|t|...
253,FBbt_00007712,254.0,,5|4|7|||1|6|0|7|||3|1|1,"right T2 leg neuropil on L3 CNS template, Wood...",A|9|c| |R|||A|b|d|o|m|i|n|a|l| |S|e|g|m|e|n|t|...
254,FBbt_00007720,255.0,,6|5|5|||7|7|8|||2|7|1,left ventromedial neuropil of tritocerebrum on...,T|2|L|e|g| |R|||T|h|o|r|a|c|i|c| |S|e|g|m|e|n|...
255,NaN,NaN,NaN,3|5|9|||3|5|1|||2|8|9,NaN,T|R|v| |L|||T|r|i|t|o|c|e|r|e|b|r|u|m| |v|e|n|...